services:
  db:
    image: mysql:8.0
    # Authentification native pour compatibilit√©
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my-agenda-database
    ports:
      - "3307:3306" # Accessible sur localhost:3307
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
