version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_agenda
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_agenda
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - agenda_net

volumes:
  mysql_data:

networks:
  agenda_net:
